swagger: "2.0"
info:
  description: "Your first API with Amazon API Gateway. This is a sample API that\
    \ integrates via HTTP with our demo Pet Store endpoints"
  version: "2023-02-01T06:38:23Z"
  title: "PetStore"
host: "a2a4d71ry9.execute-api.ap-south-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /users:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Empty"
    post:
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Empty"
    delete:
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Empty"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "URI that may access the resource"
            Access-Control-Allow-Methods:
              type: "string"
              description: "Method or methods allowed when accessing the resource"
            Access-Control-Allow-Headers:
              type: "string"
              description: "Used in response to a preflight request to indicate which\
                \ HTTP headers can be used when making the request."
    patch:
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Empty"
  /users-list:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Empty"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "URI that may access the resource"
            Access-Control-Allow-Methods:
              type: "string"
              description: "Method or methods allowed when accessing the resource"
            Access-Control-Allow-Headers:
              type: "string"
              description: "Used in response to a preflight request to indicate which\
                \ HTTP headers can be used when making the request."
definitions:
  Empty:
    type: "object"
